import streamlit as st
import pandas as pd
import plotly.express as px
import pdfplumber

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="Scope 3 Data Engine", page_icon="🌍", layout="wide")

# --- SIDEBAR ---
with st.sidebar:
    st.title("⚙️ Engine Configuration")
    
    st.markdown("**Taxonomy & Frameworks**")
    st.selectbox("Active Standard", ["GHG Protocol (2024)", "SBTi Corporate Manual", "ISO 14064"])
    st.selectbox("Logic Library", ["Scope3_Library.csv", "Standard Spend Proxy"])
    
    st.markdown("**Processing Parameters**")
    st.slider("AI Confidence Threshold", 50, 100, 85, help="Items below this confidence score will trigger human review.")
    st.checkbox("Auto-Exclude Financial Noise", value=True)
    st.checkbox("Enable Strict Audit Mode", value=True)
    
    st.markdown("---")
    st.caption("User ID: Senior ESG Auditor")
    st.caption("Deployment: Capstone V3.0 (Dynamic NLP)")

# --- HEADER ---
st.title("🏢 JATA: Scope 3 Data Preparation Engine")
st.markdown("Upload consolidated managing agent invoices to automatically extract, structure, and audit emissions-relevant data.")

# --- FILE UPLOAD ---
uploaded_files = st.file_uploader(
    "Drop PDF/CSV Invoice Documents Here",
    type=['pdf', 'csv'],
    accept_multiple_files=True
)

# --- TEXT EXTRACTION & PROCESSING ---
all_text = []
detected_items = []

if uploaded_files:
    with st.spinner(f"Ingesting and parsing {len(uploaded_files)} document(s)..."):
        for file in uploaded_files:
            if file.type == "application/pdf":
                with pdfplumber.open(file) as pdf:
                    text = ""
                    for page in pdf.pages:
                        text += page.extract_text() or ""
                    all_text.append(text)

            elif file.type == "text/csv":
                df_csv = pd.read_csv(file)
                all_text.append(df_csv.to_string())

        # --- KEYWORD DETECTION ENGINE ---
        keywords_map = {
            "electricity": "Energy Extraction",
            "water": "Utility Extraction",
            "waste": "Waste Operations",
            "cleaning": "Service Extraction",
            "kwh": "Physical Unit Found",
            "tonnes": "Physical Unit Found"
        }

        for text in all_text:
            text_lower = text.lower()
            for kw, category in keywords_map.items():
                if kw in text_lower:
                    detected_items.append(category)
        
        # Remove duplicates
        detected_items = list(set(detected_items))

    # --- SIMULATED STRUCTURED DATA (The Output) ---
    # In a fully deployed version, this dictionary would be dynamically generated by the AI passing over 'all_text'
    data = {
        "Verification Status": [
            "✅ Verified", "🚫 EXCLUDED", "✅ Verified", "⚠️ UNCLEAR",
            "✅ Verified", "✅ Verified", "⚠️ UNCLEAR", "✅ Verified",
            "🚫 EXCLUDED", "✅ Verified"
        ],
        "Line Item Description": [
            "Electricity Usage (Meter Ref: E-9921) - 891 kWh",
            "Carbon Management & Regulatory Admin Fee",
            "Monthly Chiller Maintenance - Block A",
            "Uniform & Equipment Ref: U-112",
            "General Waste Haulage (Weight: 4.25 Tonnes)",
            "Daily Office Cleaning (Level 1-10)",
            "Fogging Services - Ref: PC-55",
            "Consolidated Water Bill (Usage: 450 m3)",
            "Corporate ESG Levy",
            "Repair of Auto-door Motor Job #882"
        ],
        "Extracted Vendor": [
            "METRO ENERGY", "GLOBAL GRID", "DAIKIN", "Pending Human Input",
            "WASTERECYCLE PTE", "SPARKLE COMMERCIAL", "Pending Human Input",
            "URBAN FACILITIES", "METRO PROPERTY", "DORMA"
        ],
        "Scope 3 Categorisation": [
            "Cat 3: Fuel & Energy", "Non-Emissive", "Cat 1: Services", "Pending Resolution",
            "Cat 5: Waste", "Cat 1: Services", "Pending Resolution",
            "Cat 3: Fuel & Energy", "Non-Emissive", "Cat 1: Services"
        ],
        "Accounting Type": [
            "Activity (kWh)", "Spend-based", "Spend-based", "Spend-based",
            "Activity (Tonnes)", "Spend-based", "Spend-based",
            "Activity (m3)", "Spend-based", "Spend-based"
        ],
        "Audit Logic Rule": [
            "Metric Extraction", "Financial Noise", "Subcontractor Resolution",
            "Entity Resolution: Uncertainty", "Metric Extraction", "Subcontractor Resolution",
            "Entity Resolution: Uncertainty", "Metric Extraction", "Levy Exclusion", "Subcontractor Resolution"
        ]
    }

    df = pd.DataFrame(data)

    # --- DYNAMIC KPIs ---
    st.subheader("Batch Processing Summary")
    col1, col2, col3, col4 = st.columns(4)

    total_items = len(df)
    activity_items = df["Accounting Type"].str.contains("Activity").sum()
    activity_yield = round((activity_items / total_items) * 100, 1)
    excluded_items = (df["Verification Status"] == "🚫 EXCLUDED").sum()
    manual_hours_saved = round(total_items * 0.15, 1) # Assumes 9 mins per item manually

    col1.metric("Total Line Items", total_items, delta="Disaggregated")
    col2.metric("Manual Hours Saved", f"{manual_hours_saved} hrs", delta="-85% Time", delta_color="inverse")
    col3.metric("Excluded 'Noise' Items", excluded_items, delta="Emissions Protected")
    col4.metric("Activity Data Yield", f"{activity_yield}%", delta="High-Fidelity Hits")

    st.markdown("---")

    # --- INTERACTIVE TABS ---
    tab1, tab2, tab3, tab4 = st.tabs([
        "📝 Resolution Desk", "📊 Analytics Dashboard", "⚙️ NLP Logs", "📥 Audit Export"
    ])

    with tab1:
        st.markdown("### Human-in-the-Loop Validation")
        st.info("Review flagged items to maintain audit integrity.")
        
        # Enforcing dropdowns for governance
        edited_df = st.data_editor(
            df,
            column_config={
                "Verification Status": st.column_config.SelectboxColumn(
                    "Status", options=["✅ Verified", "⚠️ UNCLEAR", "🚫 EXCLUDED"], required=True
                )
            },
            disabled=["Line Item Description", "Accounting Type", "Audit Logic Rule"],
            use_container_width=True,
            hide_index=True
        )

    with tab2:
        st.markdown("### Footprint Composition")
        
        # Filtering out excluded items for the carbon chart
        valid_emissions_df = df[df["Verification Status"] != "🚫 EXCLUDED"]
        
        fig = px.pie(
            valid_emissions_df,
            names="Scope 3 Categorisation",
            hole=0.4,
            color_discrete_sequence=px.colors.qualitative.Prism
        )
        fig.update_layout(margin=dict(t=0, b=0, l=0, r=0), height=350)
        st.plotly_chart(fig, use_container_width=True)

    with tab3:
        st.markdown("### Extraction & Logic Logs")
        if detected_items:
            st.success(f"**Semantic Triggers Detected:** {', '.join(detected_items)}")
        
        st.code("""
[SYSTEM] Ingesting documents...
[OCR] Extracting raw text via pdfplumber.
[NLP] Applying Taxonomy Logic: Scope3_Library.csv
[RULE] Matched 'Ref: U-112' to Uncertainty Profile. Awaiting Human Input.
[RULE] Matched '891 kWh' to Category 3 Metric Extraction.
[SYSTEM] Table generation complete.
        """, language="log")
        
        # Optional: Show raw text preview
        with st.expander("View Raw Extracted Text (Debugger)"):
            for i, text in enumerate(all_text):
                st.text_area(f"Document {i+1} Output", text[:800] + "...", height=150)

    with tab4:
        st.markdown("### Final Compliance Export")
        st.markdown("Download the verified dataset for seamless API ingestion into tools like Asuene or Persefoni.")
        csv = edited_df.to_csv(index=False).encode("utf-8")
        st.download_button("Download Audit-Ready CSV", csv, "jata_scope3_output.csv", type="primary")

else:
    # Instructions shown before a file is uploaded
    st.info("👈 Configure engine settings in the sidebar, then upload procurement documents to begin analysis.")